ontologies:
    baseURI: $BASEURI
    baseURIAlias: $BASEURIALIAS
    sparql:
        config:
            serverURI: http://rdf4j:8080/rdf4j-server/
            repository: $REPOSITORIES_NAME

# Configuration for module: FileStorageModule (FileStorageConfig)
file-system:
    # File storage service (FileStorageService)
    fs:
        config:
            # Default file system storage (String)
            defaultFS: gridfs
            # Map of file storage connection definition by identifier (Map<String,FileStorageConnection>)
            connections:
                gridfs:
                    # Service implementation class for: gridfs (FileStorageConnection)
                    implementation: org.opensilex.fs.gridfs.GridFSConnection
                    config:
                        # MongoDB main host (String)
                        host: mongodb
                        # MongoDB main host port (int)
                        port: 27017
                        database: $REPOSITORIES_NAME
                local:
                    # Service implementation class for: local (FileStorageConnection)
                    implementation: org.opensilex.fs.local.LocalFileSystemConnection
                    config:
                        # Base path for file storage (String)
                        basePath: ../../opensilex-data

big-data:
    mongodb:
        config:
            host: mongodb
            port: 27017
            database: $REPOSITORIES_NAME
server:
    pathPrefix: /$OPENSILEX_PATH_PREFIX
    publicURI: "http://localhost:$HAPROXY_EXPOSED_PORT"
