# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - build
  - pages
  - integration

integration-job:
  stage: integration
  script:
    - git fetch origin pull/${CI_MERGE_REQUEST_IID}/head:pr-${CI_MERGE_REQUEST_IID}
    - git checkout pr-${CI_MERGE_REQUEST_IID} 
    - echo "Exécution des tests..." 
  rules:
    - if: $GITHUB_ACCESS == "$GITHUB_ACCESS_VALUE"


# create an docker image 
build:image: 
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - if [ -z "$IMAGE_TAG" ]; then echo "Missing IMAGE_TAG variable"; exit 1; fi 
    - docker info
    - docker build -t $DOCKER_REGISTRY/opensilex-docker-compose  --tag=registry.forgemia.inra.fr/opensilex/opensilex-docker-compose:$IMAGE_TAG .
    - docker push $DOCKER_REGISTRY/opensilex-docker-compose:$IMAGE_TAG
  when: manual

pages:
  stage: pages 
  before_script:
   - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3
   - trivy plugin install github.com/fatihtokus/scan2html
  script:
    - mkdir public 
    - trivy scan2html image $DOCKER_REGISTRY/opensilex-docker-compose:latest public/interactive_result.html
  artifacts:
    paths:
      - public
      - logs
  when: manual