# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - integration

integration-job:
  stage: integration
  before_script:
    - apt update && apt install -y git jq
  script:
    - PULL_REQUEST_NUMBER=$(echo $TRIGGER_PLAYLOAD | jq '.number')
    - PULL_REQUEST_REPO=$(echo $TRIGGER_PLAYLOAD | jq '.pull_request.base.repo.full_name')
    - git remote add upstream https://github.com/$PULL_REQUEST_REPO
    - git fetch upstream pull/${PULL_REQUEST_NUMBER}/head:pr-${PULL_REQUEST_NUMBER}
    - git checkout pr-${PULL_REQUEST_NUMBER} 
    - git config --global user.name "anonymous"
    - git config --global user.email "anonymous@opensilex.org"
    - git remote set-url origin "https://oauth2:$GITLAB_USER_CI_PAT@forgemia.inra.fr/OpenSILEX/opensilex-docker-compose.git"
    - if [  -z "`git show-ref refs/heads/pr-${PULL_REQUEST_NUMBER}`" ]; then  echo 'branch pr-${PULL_REQUEST_NUMBER} will be created!' &&  git checkout -b pr-${PULL_REQUEST_NUMBER}; else git checkout pr-${PULL_REQUEST_NUMBER} ;fi
    - git fetch origin
    - git push -f origin pr-${PULL_REQUEST_NUMBER}

  only:
    - merge_requests
   
