ontologies:
    baseURI: http://vitis-explorer.inrae.fr/
    baseURIAlias: vitis-explorer
    sparql:
        config:
            serverURI: http://opensilex-docker-rdf4j:8080/rdf4j-server/
            repository: opensilex-docker-db
# Configuration for module: FileStorageModule (FileStorageConfig)
file-system:
    # File storage service (FileStorageService)
    fs:
        config:
            # Default file system storage (String)
            defaultFS: gridfs
            # Map of file storage connection definition by identifier (Map<String,FileStorageConnection>)
            connections:
                gridfs:
                    # Service implementation class for: gridfs (FileStorageConnection)
                    implementation: org.opensilex.fs.gridfs.GridFSConnection
                    config:
                        # MongoDB main host (String)
                        host: opensilex-docker-mongodb
                        # MongoDB main host port (int)
                        port: 27017
                        database: opensilex-docker-db
                local:
                    # Service implementation class for: local (FileStorageConnection)
                    implementation: org.opensilex.fs.local.LocalFileSystemConnection
                    config:
                        # Base path for file storage (String)
                        basePath: /home/opensilex/opensilex-data
            customPath:
                datafile/: gridfs
                documents/: gridfs
big-data:
    mongodb:
        config:
            host: opensilex-docker-mongodb
            port: 27017
            database: opensilex-docker-db
server:
    pathPrefix: /vitis-explorer
    publicURI: "http://localhost:80"

front:
    versionLabel: test-version
    theme: inrae-sixtine-vigne#vigne
    homeComponent: inrae-sixtine-vigne-SixtineHomeComponent
    loginComponent: inrae-sixtine-vigne-SixtineLoginComponent
    footerComponent: inrae-sixtine-vigne-SixtineFooterComponent
    menuComponent: inrae-sixtine-vigne-SixtineMenuComponent
    headerComponent: inrae-sixtine-vigne-SixtineHeaderComponent
 
system:
  ignoredModules:
    opensilex.service.PhisWsModule: opensilex-phis.jar