ontologies:
    baseURI: http://opensilex.test/
    baseURIAlias: opensilex-sandbox
    sparql:
        config:
            serverURI: http://opensilex-docker-rdf4j:8080/rdf4j-server/
            repository: opensilex-docker-db
# Configuration for module: FileStorageModule (FileStorageConfig)
file-system:
    # File storage service (FileStorageService)
    fs:
        config:
            # Default file system storage (String)
            defaultFS: gridfs
            # Map of file storage connection definition by identifier (Map<String,FileStorageConnection>)
            connections:
                gridfs:
                    # Service implementation class for: gridfs (FileStorageConnection)
                    implementation: org.opensilex.fs.gridfs.GridFSConnection
                    config:
                        # MongoDB main host (String)
                        host: opensilex-docker-mongodb
                        # MongoDB main host port (int)
                        port: 27017
                        database: opensilex-docker-db
                local:
                    # Service implementation class for: local (FileStorageConnection)
                    implementation: org.opensilex.fs.local.LocalFileSystemConnection
                    config:
                        # Base path for file storage (String)
                        basePath: /home/opensilex/opensilex-data
            customPath:
                datafile/: gridfs
                documents/: gridfs
big-data:
    mongodb:
        config:
            host: opensilex-docker-mongodb
            port: 27017
            database: opensilex-docker-db
server:
    pathPrefix: /sandbox
    publicURI: "http://localhost:80"

front:
  versionLabel: test-version
  theme: opensilex-front#opensilex
  homeComponent: opensilex-DefaultHomeComponent
  loginComponent: opensilex-DefaultLoginComponent
  footerComponent: opensilex-DefaultFooterComponent
  menuComponent: opensilex-DefaultMenuComponent
  headerComponent: opensilex-DefaultHeaderComponent 
  dashboard:
    graph1:
      # Variable URI to use for the visualization
      variable: "dev:id/variable/air_temperature_thermometer_degreecelsius"

# ------------------------------------------------------------------------------
# Configuration for module: CoreModule (CoreConfig)
core:
  # Metrics options (MetricsConfig)
  metrics:
    # Activate access metrics (boolean)
    enableMetrics: true
    # Metrics configs about system (SystemMetricsConfig)
    system:
      # First metrics for any time depending on is time unit (int)
      timeBeforeFirstMetric: 1
      # Delay between whole system metrics (combined with corresponding TimeUnit) (int)
      delayBetweenMetrics: 2
      # Default metrics units : DAYS, HOURS, MINUTES, SECONDS are authorized (String)
      metricsTimeUnit: HOURS
    # Metrics configs about experiments (ExperimentsMetricsConfig)
    experiments:
      # First metrics for any time depending on is time unit (int)
      timeBeforeFirstMetric: 1
      # Delay between whole system metrics (combined with corresponding TimeUnit) (int)
      delayBetweenMetrics: 2
      # Default metrics units : DAYS, HOURS, MINUTES, SECONDS are authorized (String)
      metricsTimeUnit: HOURS
  sharedResourceInstances:
    - uri: http://138.102.159.36:8083/rest
      label:
          fr: "PHENOME"
          en: "PHENOME"
      accountName: admin@opensilex.org
      accountPassword: admin
    - uri: http://138.102.159.36:8082/rest
      label:
          fr: "EMPHASIS"
          en: "EMPHASIS"
      accountName: admin@opensilex.org
      accountPassword: admin
    - uri: https://vitioeno.mistea.inrae.fr/resource/rest
      label:
          fr: "VitiOeno"
          en: "VitiOeno"
      accountName: admin@opensilex.org
      accountPassword: admin

system:
  ignoredModules:
    opensilex.service.PhisWsModule: opensilex-phis.jar