system:
  ignoredModules:
    opensilex.service.PhisWsModule: opensilex-phis.jar
data-analysis:
  scientificAppServer:
    config:
      enable: true
      host: localhost
      port: 8004
      #landingPage: /proxy
      # publicServerURL: https://vitioeno.mistea.inrae.fr/proxy
      # serverServletContextPath: /proxy
      # Docker container prefix name (multiple shinyproxy on same server) (String)
      shinyProxyContainerPrefix: vitioeno
      # Docker network name (String)
      shinyProxyNetwork: vitioeno-shiny-proxy-network
