ontologies:
    baseURI: $BASEURI
    baseURIAlias: $BASEURIALIAS
    sparql:
        config:
            serverURI: http://localhost:$RDF4J_EXPOSED_PORT/rdf4j-server/
            repository: $REPOSITORIES_NAME
# Configuration for module: FileStorageModule (FileStorageConfig)
file-system:
    # File storage service (FileStorageService)
    fs:
        config:
            # Default file system storage (String)
            defaultFS: $OPENSILEX_FILESYSTEM
            # Map of file storage connection definition by identifier (Map<String,FileStorageConnection>)
            connections:
                gridfs:
                    # Service implementation class for: gridfs (FileStorageConnection)
                    implementation: org.opensilex.fs.gridfs.GridFSConnection
                    config:
                        # MongoDB main host (String)
                        host: localhost
                        # MongoDB main host port (int)
                        port: $MONGO_EXPOSED_PORT
                        database: $REPOSITORIES_NAME
                local:
                    # Service implementation class for: local (FileStorageConnection)
                    implementation: org.opensilex.fs.local.LocalFileSystemConnection
                    config:
                        # Base path for file storage (String)
                        basePath: $INTERNAL_DATA_DIRECTORY
            customPath:
                datafile/: $DATAFILE_OPENSILEX_FILESYSTEM
                documents/: $DOCUMENTS_OPENSILEX_FILESYSTEM
big-data:
    mongodb:
        config:
            host: localhost
            port: $MONGO_EXPOSED_PORT
            database: $REPOSITORIES_NAME
server:
    pathPrefix: /$OPENSILEX_PATH_PREFIX
    publicURI: "$OPENSILEX_HOST_URL"

front:
    versionLabel: $VERSION_LABEL
    theme: $OPENSILEX_CONFIG_THEME
    homeComponent: $OPENSILEX_CONFIG_HOMECOMPONENT
    loginComponent: $OPENSILEX_CONFIG_LOGINCOMPONENT
    footerComponent: $OPENSILEX_CONFIG_FOOTERCOMPONENT
    menuComponent: $OPENSILEX_CONFIG_MENUCOMPONENT
    headerComponent: $OPENSILEX_CONFIG_HEADERCOMPONENT
